name = "only-vibes"
main = "worker/index.ts"
compatibility_date = "2025-07-11"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "only-vibes-db"
database_id = "d4303e3d-790a-41ed-b794-45c3b76c5c18"
migrations_dir = "./drizzle/migrations"

[observability]
enabled = true
head_sampling_rate = 1
